default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

rds: &rds
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

development:
  <<: *default
  database: spree_alchemy_development

test:
  <<: *default
  database: spree_alchemy_test

production:
  <<: *rds